config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get "articles", to: "articles#index"
  get "articles/new", to: "articles#new", as: :new_articles
  get "articles/:id", to: "articles#show"
  get "articles/:id/edit", to: "articles#edit"
  patch "articles/:id", to: "articles#update", as: :article
  post "articles", to: "articles#create"
  delete "articles/:id", to: "articles#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :find_article, except: [:new,:create,:index]

    def index
        @articles = Article.all
    end

    def update
        @article.update(title: params[:article][:title], content: params[:article][:content])
        redirect_to @article
    end

    def edit
    end

    def show
    end
    
    def new
        @article = Article.new
    end

    def create
        @article = Article.create(title: params[:article][:title], content: params[:article][:content])
        render json:@article
    end

    def destroy
        @article.destroy
        redirect_to root_path
    end

    def find_article
        @article = Article.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div class="card padding margin-top">
    <h3 class="text-uppercase"> <%= article.title %> </h3>
    <h4 class="text-secondary"> <%= article.created_at %> </h4>
    <%= link_to "Ver más", article %>
</div>

app/views/articles/_form.html.erb
<%=form_with(model: @article, local: true) do |form|%>
    <div class="field">
        <%=form.label :title%>
        <%=form.text_field :title%>
    </div>

    <div class="field">
        <%=form.label :content%>
        <%=form.rich_text_area :content%>
    </div>

    <div>
        <%=form.submit%>
    </div>
<%end%>

app/views/articles/edit.html.erb
<div class="small-container center-block">
    <%= render "articles/form" %>
</div>

app/views/articles/index.html.erb
<div class="large-container center-block">
    <h1>Mis articulos</h1>
    <%= render @articles %>
</div>

app/views/articles/new.html.erb
<div class="small-container center-block">
    <%= render "articles/form" %>
</div>

app/views/articles/show.html.erb
<h1> <%= @article.title %> </h1>
<div>
    <%= @article.content %>
</div>
<div>
    <%= link_to "Eliminar el articulo", @article, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Hola mundo :)</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyOnRailsUdemy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="notice alert-primary"><%= notice %></p>
    <%end%>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <%end%>
    <%= render "partials/nav" %>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav class="nav bg-ligth padding">
    <%= link_to "Inicio", root_path, class:"nav-link" %></li>
    <%= link_to "Todos los articulos", articles_path, class:"nav-link" %></li>
    <%= link_to "Escribir", new_articles_path, class:"nav-link" %></li>
</nav>